Repository terrestris/react-geo, pull requests merged in 2018-05, with the labels that each got.

#622 make sure only the most recent request data is used
  src/Field/WfsSearch/WfsSearch.jsx
  src/Field/WfsSearch/WfsSearch.spec.jsx
Labels: bug

#632 Collect coverage from src directory only
  jest.config.js
Labels: dev setup

#634 Better configuration for coverage collection
  jest.config.js
Labels: refactoring

#654 Remove unneeded info wrt the non-existant vulnerability
  README.md
Labels: documentation
